// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupProject(ctx *pulumi.Context, args *GetProjectArgs) (*GetProjectResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["name"] = args.Name
	}
	outputs, err := ctx.Invoke("mongodbatlas:index/getProject:getProject", inputs)
	if err != nil {
		return nil, err
	}
	return &GetProjectResult{
		ClusterCount: outputs["clusterCount"],
		Created: outputs["created"],
		Name: outputs["name"],
		OrgId: outputs["orgId"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getProject.
type GetProjectArgs struct {
	Name interface{}
}

// A collection of values returned by getProject.
type GetProjectResult struct {
	ClusterCount interface{}
	Created interface{}
	Name interface{}
	OrgId interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
